### ISSUE TITLE
Filename reporting in parse error

### ISSUE THREAD

**Issue by robcolburn** [sindresorhus/gulp-react#33]
I'm not sure where exactly to report this (`gulp-jscs`, `jscs`, `espirma-fb`, `jstransform`, or `react-tools`), but I figure @sindresorhus runs most of them, so this isn't a bad place to start.

My linting task is crashing on a parsing error. In particular, I had a file with duplicate es6 methods in the same class. Yeah, that's a goofy situation, probably a bad git merge, oh well.

Anyway, the issue is that we're crashing in a very inconveniant way.  Gulp is pushing a bunch of files down the chain, and by the time the error spits out, I don't know what's crashing.

```js
function jsfiles () {
  return merge(
    gulp.src([
      "./*.js",
      "./lib/*.js",
      "./components/**/*.js"
    ]),
    gulp.src('./components/**/*.jsx')
      .pipe(react({es6module: true}))
  );
}
gulp.task('jscs', function() {
  return jsfiles()
    .pipe(jscs());
});
```

Here's the error
```
[10:50:41] Starting 'jscs'...
{}

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Parse Error: Line 93: Duplicate data property in object literal not allowed in strict mode {}
    at throwError (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2813:21)
    at throwErrorTolerant (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2826:24)
    at parseObjectInitialiser (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3400:29)
    at parsePrimaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3554:20)
    at parseLeftHandSideExpressionAllowCall (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3657:61)
    at parsePostfixExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3697:20)
    at parseUnaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3764:16)
    at parseBinaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3854:16)
    at parseConditionalExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3914:16)
    at parseAssignmentExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:4167:16)
```

**Comment by sindresorhus** [comment]
Try removing the `jscs` gulp task to at least see if that's the one causing problems.

This task should in theory report all errors with filenames: https://github.com/sindresorhus/gulp-react/blob/726daeebf3ebd93d27f04389e12345e711890aa1/index.js#L42

You also need to attach an error listener: https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md

**Comment by robcolburn** [comment]
Yeah, that was it. Not exactly pretty, but it works:
```js
function jsfiles () {
  return merge(
    gulp.src([
      "./*.js",
      "./lib/*.js",
      "./components/**/*.js"
    ]),
    gulp.src('./components/**/*.jsx')
      .pipe(react({es6module: true}))
      .on('error', console.error.bind(console))
  );
}
```

```
[11:52:43] Starting 'jscs'...
{ [Error: Parse Error: Line 93: Duplicate data property in object literal not allowed in strict mode]
  index: 2850,
  lineNumber: 93,
  column: 4,
  description: 'Duplicate data property in object literal not allowed in strict mode',
  name: 'Error',
  message: 'Parse Error: Line 93: Duplicate data property in object literal not allowed in strict mode',
  stack: 'Error: Parse Error: Line 93: Duplicate data property in object literal not allowed in strict mode\n    at throwError (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2813:21)\n    at throwErrorTolerant (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2825:24)\n    at parseObjectInitialiser (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3399:29)\n    at parsePrimaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3553:20)\n    at parseLeftHandSideExpressionAllowCall (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3656:61)\n    at parsePostfixExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3696:20)\n    at parseUnaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3763:16)\n    at parseBinaryExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3853:16)\n    at parseConditionalExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:3913:16)\n    at parseAssignmentExpression (PROJ/node_modules/gulp-react/node_modules/react-tools/node_modules/jstransform/node_modules/esprima-fb/esprima.js:4166:16)',
  fileName: 'PROJ/components/snl40/routes/playlist/playlist.view.jsx',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-react' }
```

So, without an error listener, the plugin bubbles out to node, makes sense.
